# docker-compose.yml
version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static  # Добавляем volume для статики фронтенда
    command: >
      sh -c "npm run build && 
             cp -r /app/build/. /frontend_static/."  # Команда копирования

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles  # Монтируем общий volume
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
